# cloudbuild.yaml

steps:
  # 1. Build da Imagem Docker
  # Usamos o builder 'docker'. Ele está pré-autenticado para o Artifact Registry.
  - id: 'Build and tag image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/artluz-landing-page-${BRANCH_NAME}:${COMMIT_SHA}'
      - '.' # Build a partir do Dockerfile no diretório atual

  # 2. Push da Imagem para o Artifact Registry
  - id: 'Push to Artifact Registry'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/artluz-landing-page-${BRANCH_NAME}:${COMMIT_SHA}'

  # 3. Deploy no Cloud Run
  # Usamos o builder 'gcloud' para executar o deploy.
  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
        # Comando gcloud run deploy
        gcloud run deploy artluz-landing-page-${BRANCH_NAME} \
            --region ${_REGION} \
            --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/artluz-landing-page-${BRANCH_NAME}:${COMMIT_SHA} \
            --runtime=${_RUNTIME} \
            --cpu=${_CPU} \
            --service-account=${_SERVICE_ACCOUNT} \
            --memory=${_MEMORY} \
            --min-instances=${_MIN_INSTANCES} \
            --max-instances=${_MAX_INSTANCES} \
            --ingress=${_INGRESS} \
            --timeout=${_TIMEOUT} \
            --platform managed \
            --allow-unauthenticated

substitutions:
  _REGION: 'southamerica-east1'
  _RUNTIME: 'nodejs20'
  _CPU: "1"
  _SERVICE_ACCOUNT: "deploy-cloud-run-583@artluz.iam.gserviceaccount.com"
  _MEMORY: "256Mi"
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "default" # 'default' ou um número específico (ex: "10")
  _INGRESS: "all"
  _TIMEOUT: "30s"
  # BRANCH_NAME e COMMIT_SHA são fornecidos automaticamente pelo Cloud Build

options:
  logging: CLOUD_LOGGING_ONLY