steps:
  - id: 'Docker authenticate'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
        gcloud auth configure-docker ${_REGION}-docker.pkg.dev --quiet || exit 1

  
  - id: 'Build and push to Artifact Registry'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |-

        docker build -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-deploy/artluz-landing-page-${BRANCH_NAME}:$COMMIT_SHA . || exit 1
        docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-deploy/artluz-landing-page-${BRANCH_NAME}:$COMMIT_SHA || exit 1

  - id: 'Create Build'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
        # Deploy function
        gcloud run deploy artluz-landing-page-${BRANCH_NAME} \
            --region ${_REGION} \
            --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-deploy/artluz-landing-page-${BRANCH_NAME}:$COMMIT_SHA \
            --runtime=${_RUNTIME} \
            --cpu=${_CPU} \
            --memory=${_MEMORY}\
            --min-instances=${_MIN_INSTANCES} \
            --max-instances=${_MAX_INSTANCES} \
            --ingress=${_INGRESS} \
            --timeout=${_TIMEOUT} \
            --platform managed \
            --allow-unauthenticated 

substitutions:
  _REGION: 'southamerica-east1'
  _RUNTIME: 'nodejs20'
  _CPU: "1"
  _MEMORY: "256Mi"
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "default"
  _INGRESS: "all"
  _TIMEOUT: "30s"

options:
  logging: CLOUD_LOGGING_ONLY